config/routes.rb
Rails.application.routes.draw do

  get 'orderitems/index'
  get 'products/index'
	root to: 'categories#index'


	resources :categories, only: [:index] do
		resources :products, only: [:index] 
	end


	get '/cart', to: 'order_items#index'
	resources :order_items, path: '/cart/items'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
	has_many :product_categories
	has_many :products, through: :product_categories

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	 belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
		validates :title, presence: true


		has_many :product_categories
		has_many :categories, through: :product_categories
		has_many :variants, class_name: 'ProductVariant'
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
end

app/models/shopping_cart.rb
class ShoppingCart

	def initialize(token:)
		@token = token				
	end

	def order 
		@order ||= Order.find_or_create_by(token: @token) do |order|
			order.sub_total = 0
		end		
	end

	def add_item(product_id:, quantity: 1)
		product = Product.find(product_id)

		order_item = order.items.find_or_create_by(
			product_id: product_id
		)

		order_item.price = product.price 
		order_item.quantity = quantity

		order_item.save
		
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :current_cart
	def current_cart
		@current_cart ||= ShoppingCart.new(token: cart_token)		
	end
	helper_method :current_cart

	private

	def cart_token
		return @cart_token unless @cart_token.nil?

		session[:cart_token] ||= SecureRandom.hex(8)
		@cart_token = session[:cart_token]
		
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.joins(:products).select('categories.*, count(products.id) as products_count').group('categories.id').order(:title)
		
	end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
	def index
		
	end

  def create
  	current_cart.add_item(
  		product_id: params[:product_id],
  		quantity: params[:quantity]
  		)

  	redirect_to cart_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@category = Category.find(params[:category_id])
  	@products = @category.products.includes(:variants).order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<h2>Categories (<%= @categories.length %>)</h2>

<ol>
	<% @categories.each do |category| %>
	<li>
		<%= link_to category_products_path(category) do %>
		<%= category.title %>
		(<%= category.products_count %> products)
		<% end -%>
	</li>
	<% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orderitems/index.html.erb
<h1>Orderitems#index</h1>
<p>Find me in app/views/orderitems/index.html.erb</p>

app/views/products/index.html.erb
<h2>
	<%= link_to 'categories', root_path %>
	<%= @category.title %>/
	products
</h2>

<ol>
	<% @products.each do |product| %>
	<li>
		<%= product.title %> (<%= product.price %> Rupees)

		<%= form_tag order_items_path do %>
		<%= hidden_field_tag :product_id, product.id %>
		<%= number_field_tag :quantity, 1 %>
		<%= submit_tag "add to cart" %>
		<% end %>







		<ul>
			<% product.variants.each do  |variant| %>
			<li>
				<%= variant.title %>(<%= variant.price %>)
			</li>
			<% end %>
		</ul>
	</li>
	<% end %>
</ol>